# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=100)),
                ('copies', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('usertype', models.CharField(choices=[('Librerian', 'Librerian'), ('Student', 'Student')], default='aaa', max_length=30)),
            ],
        ),
    ]
