# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
