# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180713_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='issued_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_book', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=30)),
                ('issue_date', models.CharField(max_length=30)),
                ('return_date', models.CharField(max_length=30)),
            ],
        ),
    ]
