# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_issued_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_book',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
    ]
