# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_issued_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issued_book',
            name='book_id',
        ),
    ]
