# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 21, 16, 15, 47, 437480)),
        ),
        migrations.AlterField(
            model_name='issued_book',
            name='return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 5, 16, 15, 47, 437510)),
        ),
    ]
