# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180721_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 22, 6, 45, 16, 159593)),
        ),
        migrations.AlterField(
            model_name='issued_book',
            name='issued_book',
            field=models.CharField(default='not_picked', max_length=30),
        ),
        migrations.AlterField(
            model_name='issued_book',
            name='return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 6, 6, 45, 16, 159627)),
        ),
    ]
